# Generated by Django 2.1.3 on 2018-12-17 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'AffectedDt',
                'db_table': 'affected_dt',
            },
        ),
        migrations.CreateModel(
            name='AgeAtOnsetClassificationDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'AgeAtOnsetClassificationDt',
                'db_table': 'age_at_onset_classification_dt',
            },
        ),
        migrations.CreateModel(
            name='AgeAtOnsetOfOcularSymptomDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'AgeAtOnsetOfOcularSymptomDt',
                'db_table': 'age_at_onset_of_ocular_symptom_dt',
            },
        ),
        migrations.CreateModel(
            name='AgeAtTheInitialDiagnosisClassificationDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'AgeAtTheInitialDiagnosisClassificationDt',
                'db_table': 'age_at_the_initial_diagnosis_classification_dt',
            },
        ),
        migrations.CreateModel(
            name='AgeAtTheInitialDiagnosisDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'AgeAtTheInitialDiagnosisDt',
                'db_table': 'age_at_the_initial_diagnosis_dt',
            },
        ),
        migrations.CreateModel(
            name='AgeCategoryDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'AgeCategoryDt',
                'db_table': 'age_category_dt',
            },
        ),
        migrations.CreateModel(
            name='AgeForSurgeryDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'AgeForSurgeryDt',
                'db_table': 'age_for_surgery_dt',
            },
        ),
        migrations.CreateModel(
            name='AiDiagnosisForAgeRelatedMacularDegenerationDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'AiDiagnosisForAgeRelatedMacularDegenerationDt',
                'db_table': 'ai_diagnosis_for_age_related_macular_degeneration_dt',
            },
        ),
        migrations.CreateModel(
            name='AiDiagnosisForCornealDiseasesDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'AiDiagnosisForCornealDiseasesDt',
                'db_table': 'ai_diagnosis_for_corneal_diseases_dt',
            },
        ),
        migrations.CreateModel(
            name='AiDiagnosisForDiabeticRetinopathyDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'AiDiagnosisForDiabeticRetinopathyDt',
                'db_table': 'ai_diagnosis_for_diabetic_retinopathy_dt',
            },
        ),
        migrations.CreateModel(
            name='AiDiagnosisForGlaucomaDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'AiDiagnosisForGlaucomaDt',
                'db_table': 'ai_diagnosis_for_glaucoma_dt',
            },
        ),
        migrations.CreateModel(
            name='AiDiagnosisForInheritedRetinalDiseasesDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'AiDiagnosisForInheritedRetinalDiseasesDt',
                'db_table': 'ai_diagnosis_for_inherited_retinal_diseases_dt',
            },
        ),
        migrations.CreateModel(
            name='AlleleFrequencyDatabaseDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'AlleleFrequencyDatabaseDt',
                'db_table': 'allele_frequency_database_dt',
            },
        ),
        migrations.CreateModel(
            name='AnalysisDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'AnalysisDt',
                'db_table': 'analysis_dt',
            },
        ),
        migrations.CreateModel(
            name='AxialLengthClassificationDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'AxialLengthClassificationDt',
                'db_table': 'axial_length_classification_dt',
            },
        ),
        migrations.CreateModel(
            name='AxialLengthDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'AxialLengthDt',
                'db_table': 'axial_length_dt',
            },
        ),
        migrations.CreateModel(
            name='BilateralDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'BilateralDt',
                'db_table': 'bilateral_dt',
            },
        ),
        migrations.CreateModel(
            name='ChromosomeDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'ChromosomeDt',
                'db_table': 'chromosome_dt',
            },
        ),
        migrations.CreateModel(
            name='ConsanguineousDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'ConsanguineousDt',
                'db_table': 'consanguineous_dt',
            },
        ),
        migrations.CreateModel(
            name='CountryOfOriginDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'CountryOfOriginDt',
                'db_table': 'country_of_origin_dt',
            },
        ),
        migrations.CreateModel(
            name='DiseaseDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'DiseaseDt',
                'db_table': 'disease_dt',
            },
        ),
        migrations.CreateModel(
            name='DnaExtractionInProcessDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'DnaExtractionInProcessDt',
                'db_table': 'dna_extraction_in_process_dt',
            },
        ),
        migrations.CreateModel(
            name='ElectrophysiologicalFindingsDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'ElectrophysiologicalFindingsDt',
                'db_table': 'electrophysiological_findings_dt',
            },
        ),
        migrations.CreateModel(
            name='EthnicityDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'EthnicityDt',
                'db_table': 'ethnicity_dt',
            },
        ),
        migrations.CreateModel(
            name='ExonDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'ExonDt',
                'db_table': 'exon_dt',
            },
        ),
        migrations.CreateModel(
            name='FamilyHistoryDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'FamilyHistoryDt',
                'db_table': 'family_history_dt',
            },
        ),
        migrations.CreateModel(
            name='FluctuationDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'FluctuationDt',
                'db_table': 'fluctuation_dt',
            },
        ),
        migrations.CreateModel(
            name='FullFieldElectrophysiologicalGroupingDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'FullFieldElectrophysiologicalGroupingDt',
                'db_table': 'full_field_electrophysiological_grouping_dt',
            },
        ),
        migrations.CreateModel(
            name='GeneDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'GeneDt',
                'db_table': 'gene_dt',
            },
        ),
        migrations.CreateModel(
            name='HcOnMedicationOrNotInsulinDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'HcOnMedicationOrNotInsulinDt',
                'db_table': 'hc_on_medication_or_not_insulin_dt',
            },
        ),
        migrations.CreateModel(
            name='HcOnMedicationOrNotStatinDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'HcOnMedicationOrNotStatinDt',
                'db_table': 'hc_on_medication_or_not_statin_dt',
            },
        ),
        migrations.CreateModel(
            name='InheritanceDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'InheritanceDt',
                'db_table': 'inheritance_dt',
            },
        ),
        migrations.CreateModel(
            name='InstituteDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_id', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'InstituteDt',
                'db_table': 'institute_dt',
            },
        ),
        migrations.CreateModel(
            name='IntraocularPressureClassificationDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'IntraocularPressureClassificationDt',
                'db_table': 'intraocular_pressure_classification_dt',
            },
        ),
        migrations.CreateModel(
            name='IntraocularPressureDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'IntraocularPressureDt',
                'db_table': 'intraocular_pressure_dt',
            },
        ),
        migrations.CreateModel(
            name='LensDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'LensDt',
                'db_table': 'lens_dt',
            },
        ),
        migrations.CreateModel(
            name='MultifocalElectrophysiologicalGroupingDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'MultifocalElectrophysiologicalGroupingDt',
                'db_table': 'multifocal_electrophysiological_grouping_dt',
            },
        ),
        migrations.CreateModel(
            name='MutationDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'MutationDt',
                'db_table': 'mutation_dt',
            },
        ),
        migrations.CreateModel(
            name='NumberOfAffectedMembersInTheSamePedigreeDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'NumberOfAffectedMembersInTheSamePedigreeDt',
                'db_table': 'number_of_affected_members_in_the_same_pedigree_dt',
            },
        ),
        migrations.CreateModel(
            name='NumberOfSurgeryDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'NumberOfSurgeryDt',
                'db_table': 'number_of_surgery_dt',
            },
        ),
        migrations.CreateModel(
            name='OcularComplicationDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OcularComplicationDt',
                'db_table': 'ocular_complication_dt',
            },
        ),
        migrations.CreateModel(
            name='OcularMedicationInternalDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OcularMedicationInternalDt',
                'db_table': 'ocular_medication_internal_dt',
            },
        ),
        migrations.CreateModel(
            name='OcularMedicationTopicalDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OcularMedicationTopicalDt',
                'db_table': 'ocular_medication_topical_dt',
            },
        ),
        migrations.CreateModel(
            name='OcularSurgeriesCataractDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OcularSurgeriesCataractDt',
                'db_table': 'ocular_surgeries_cataract_dt',
            },
        ),
        migrations.CreateModel(
            name='OcularSurgeriesCorneaDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OcularSurgeriesCorneaDt',
                'db_table': 'ocular_surgeries_cornea_dt',
            },
        ),
        migrations.CreateModel(
            name='OcularSurgeriesGlaucomaDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OcularSurgeriesGlaucomaDt',
                'db_table': 'ocular_surgeries_glaucoma_dt',
            },
        ),
        migrations.CreateModel(
            name='OcularSurgeriesLasersDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OcularSurgeriesLasersDt',
                'db_table': 'ocular_surgeries_lasers_dt',
            },
        ),
        migrations.CreateModel(
            name='OcularSurgeriesRetinaDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OcularSurgeriesRetinaDt',
                'db_table': 'ocular_surgeries_retina_dt',
            },
        ),
        migrations.CreateModel(
            name='OcularSurgeriesVitreousInfectionDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OcularSurgeriesVitreousInfectionDt',
                'db_table': 'ocular_surgeries_vitreous_infection_dt',
            },
        ),
        migrations.CreateModel(
            name='OcularSymptomDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OcularSymptomDt',
                'db_table': 'ocular_symptom_dt',
            },
        ),
        migrations.CreateModel(
            name='OnMedicationOrNotDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OnMedicationOrNotDt',
                'db_table': 'on_medication_or_not_dt',
            },
        ),
        migrations.CreateModel(
            name='OphthalmicMedicationSubtenonOrSubconjunctivalInjectionDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OphthalmicMedicationSubtenonOrSubconjunctivalInjectionDt',
                'db_table': 'ophthalmic_medication_subtenon_or_subconjunctival_injection_dt',
            },
        ),
        migrations.CreateModel(
            name='OphthalmologyAgeRelatedMacularDegenerationDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OphthalmologyAgeRelatedMacularDegenerationDt',
                'db_table': 'ophthalmology_age_related_macular_degeneration_dt',
            },
        ),
        migrations.CreateModel(
            name='OphthalmologyCataractDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OphthalmologyCataractDt',
                'db_table': 'ophthalmology_cataract_dt',
            },
        ),
        migrations.CreateModel(
            name='OphthalmologyCornealDiseasesDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OphthalmologyCornealDiseasesDt',
                'db_table': 'ophthalmology_corneal_diseases_dt',
            },
        ),
        migrations.CreateModel(
            name='OphthalmologyDiableticRetinopathyDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OphthalmologyDiableticRetinopathyDt',
                'db_table': 'ophthalmology_diabletic_retinopathy_dt',
            },
        ),
        migrations.CreateModel(
            name='OphthalmologyGlaucomaDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OphthalmologyGlaucomaDt',
                'db_table': 'ophthalmology_glaucoma_dt',
            },
        ),
        migrations.CreateModel(
            name='OphthalmologyMyopiaDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OphthalmologyMyopiaDt',
                'db_table': 'ophthalmology_myopia_dt',
            },
        ),
        migrations.CreateModel(
            name='OphthalmologyNormalDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OphthalmologyNormalDt',
                'db_table': 'ophthalmology_normal_dt',
            },
        ),
        migrations.CreateModel(
            name='OphthalmologyOthersDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OphthalmologyOthersDt',
                'db_table': 'ophthalmology_others_dt',
            },
        ),
        migrations.CreateModel(
            name='OphthalmologyRetinalArteryVeinOcculusionDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OphthalmologyRetinalArteryVeinOcculusionDt',
                'db_table': 'ophthalmology_retinal_artery_vein_occulusion_dt',
            },
        ),
        migrations.CreateModel(
            name='OphthalmologyUveitisDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OphthalmologyUveitisDt',
                'db_table': 'ophthalmology_uveitis_dt',
            },
        ),
        migrations.CreateModel(
            name='OriginPrefectureInJapanDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'OriginPrefectureInJapanDt',
                'db_table': 'origin_prefecture_in_japan_dt',
            },
        ),
        migrations.CreateModel(
            name='PatientCandidateGeneMutationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_old_new', models.CharField(blank=True, max_length=1, null=True)),
                ('candidate_mutation', models.CharField(blank=True, max_length=45, null=True)),
                ('candidate_gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.GeneDt')),
            ],
            options={
                'verbose_name_plural': 'PatientCandidateGeneMutationInfo',
                'db_table': 'patient_candidate_gene_mutation_info',
            },
        ),
        migrations.CreateModel(
            name='PatientCausativeGeneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_old_new', models.CharField(blank=True, max_length=1, null=True)),
                ('position', models.CharField(blank=True, max_length=45, null=True)),
                ('transcript', models.CharField(blank=True, max_length=45, null=True)),
                ('caus_mutation_nucleotide_change_amino_acid_change', models.CharField(blank=True, max_length=45, null=True)),
                ('caus_gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.GeneDt')),
                ('chromosome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.ChromosomeDt')),
                ('exon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.ExonDt')),
            ],
            options={
                'verbose_name_plural': 'PatientCausativeGeneInfo',
                'db_table': 'patient_causative_gene_info',
            },
        ),
        migrations.CreateModel(
            name='PatientCausativeGeneInfoEthnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq_ethnicity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.AlleleFrequencyDatabaseDt')),
                ('patient_causative_gene_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ophthalmology.PatientCausativeGeneInfo')),
            ],
            options={
                'verbose_name_plural': 'PatientCausativeGeneInfoEthnicity',
                'db_table': 'patient_causative_gene_info_ethnicity',
            },
        ),
        migrations.CreateModel(
            name='PatientCausativeGeneInfoLocalPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq_local_population', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.AlleleFrequencyDatabaseDt')),
                ('patient_causative_gene_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ophthalmology.PatientCausativeGeneInfo')),
            ],
            options={
                'verbose_name_plural': 'PatientCausativeGeneInfoLocalPopulation',
                'db_table': 'patient_causative_gene_info_local_population',
            },
        ),
        migrations.CreateModel(
            name='PatientGeneralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=45)),
                ('pedigree_chart', models.FileField(upload_to='')),
                ('sample_id', models.CharField(max_length=45)),
                ('birth_year_month', models.DateTimeField(blank=True, null=True, verbose_name=django.db.models.deletion.SET_NULL)),
                ('registration_date', models.DateTimeField(blank=True, null=True, verbose_name=django.db.models.deletion.SET_NULL)),
                ('dna_sample_collection_date', models.DateTimeField(blank=True, null=True, verbose_name=django.db.models.deletion.SET_NULL)),
                ('registration', models.CharField(blank=True, max_length=45, null=True)),
                ('gene_inheritance_mutation_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('overall_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('affected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophthalmology.AffectedDt')),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.AnalysisDt')),
                ('bilateral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophthalmology.BilateralDt')),
                ('consanguineous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophthalmology.ConsanguineousDt')),
                ('country_of_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientgeneralinfo_requests_created2', to='ophthalmology.CountryOfOriginDt')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophthalmology.DiseaseDt')),
                ('dna_extraction_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.DnaExtractionInProcessDt')),
                ('ethnic_of_father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientgeneralinfo_requests_created3', to='ophthalmology.EthnicityDt')),
                ('ethnic_of_mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientgeneralinfo_requests_created6', to='ophthalmology.EthnicityDt')),
                ('ethnicity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientgeneralinfo_requests_created1', to='ophthalmology.EthnicityDt')),
                ('family_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophthalmology.FamilyHistoryDt')),
                ('flactuation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophthalmology.FluctuationDt')),
                ('gene_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophthalmology.GeneDt')),
                ('inheritance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientgeneralinfo_requests_created', to='ophthalmology.InheritanceDt')),
                ('inheritance_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientgeneralinfo_requests_created3', to='ophthalmology.InheritanceDt')),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophthalmology.InstituteDt')),
                ('mutation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophthalmology.MutationDt')),
                ('number_of_affected_members_in_the_same_pedigree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophthalmology.NumberOfAffectedMembersInTheSamePedigreeDt')),
                ('ocular_symptom_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientgeneralinfo_requests_created', to='ophthalmology.OcularSymptomDt')),
                ('ocular_symptom_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientgeneralinfo_requests_created33', to='ophthalmology.OcularSymptomDt')),
                ('ocular_symptom_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientgeneralinfo_requests_created11', to='ophthalmology.OcularSymptomDt')),
                ('origin_of_father_in_japan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientgeneralinfo_requests_created', to='ophthalmology.OriginPrefectureInJapanDt')),
                ('origin_of_mother_in_japan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientgeneralinfo_requests_created9', to='ophthalmology.OriginPrefectureInJapanDt')),
                ('origin_prefecture_in_japan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophthalmology.OriginPrefectureInJapanDt')),
                ('original_country_of_father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientgeneralinfo_requests_created5', to='ophthalmology.CountryOfOriginDt')),
                ('original_country_of_mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientgeneralinfo_requests_created6', to='ophthalmology.CountryOfOriginDt')),
            ],
            options={
                'verbose_name_plural': 'PatientGeneralInfo',
                'db_table': 'patient_general_info',
            },
        ),
        migrations.CreateModel(
            name='PatientGeneralInfoFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.CharField(max_length=45)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ophthalmology.PatientGeneralInfo')),
            ],
            options={
                'verbose_name_plural': 'PatientGeneralInfoFamily',
                'db_table': 'patient_general_info_family',
            },
        ),
        migrations.CreateModel(
            name='PatientGeneralInfoMultiVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('field_direction', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ophthalmology.PatientGeneralInfo')),
            ],
            options={
                'verbose_name_plural': 'PatientGeneralInfoMultiVisit',
                'db_table': 'patient_general_info_multi_visit',
            },
        ),
        migrations.CreateModel(
            name='PatientGeneralInfoMultiVisitOphthalmology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('field_direction', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ophthalmology.PatientGeneralInfo')),
            ],
            options={
                'verbose_name_plural': 'PatientGeneralInfoMultiVisitOphthalmology',
                'db_table': 'patient_general_info_multi_visit_ophthalmology',
            },
        ),
        migrations.CreateModel(
            name='PatientGeneralInfoMultiVisitOphthalmologyAi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('field_direction', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ophthalmology.PatientGeneralInfo')),
            ],
            options={
                'verbose_name_plural': 'PatientGeneralInfoMultiVisitOphthalmologyAi',
                'db_table': 'patient_general_info_multi_visit_ophthalmology_ai',
            },
        ),
        migrations.CreateModel(
            name='PatientGeneralInfoMultiVisitOphthalmologyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('field_direction', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ophthalmology.PatientGeneralInfo')),
            ],
            options={
                'verbose_name_plural': 'PatientGeneralInfoMultiVisitOphthalmologyImages',
                'db_table': 'patient_general_info_multi_visit_ophthalmology_images',
            },
        ),
        migrations.CreateModel(
            name='PatientGeneralInfoOphthalmology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_middle_results', models.FileField(upload_to='')),
                ('vcf_whole_exome_sequencing', models.FileField(upload_to='')),
                ('vcf_whole_genome_sequencing', models.FileField(upload_to='')),
                ('gene_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('age_at_onset_of_ocul_symp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.AgeAtOnsetOfOcularSymptomDt')),
                ('age_at_the_init_diag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.AgeAtTheInitialDiagnosisDt')),
                ('age_at_the_init_diag_clas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.AgeAtTheInitialDiagnosisClassificationDt')),
                ('age_catrct_surgery_perf_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.AgeForSurgeryDt')),
                ('age_catrct_surgery_perf_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.AgeForSurgeryDt')),
                ('no_catrct_surgery_perf_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.NumberOfSurgeryDt')),
                ('no_catrct_surgery_perf_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.NumberOfSurgeryDt')),
                ('ocul_surgeries_catrct_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.OcularSurgeriesCataractDt')),
                ('ocul_surgeries_catrct_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.OcularSurgeriesCataractDt')),
                ('onset_of_diease_clas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.AgeAtOnsetClassificationDt')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ophthalmology.PatientGeneralInfo')),
            ],
            options={
                'verbose_name_plural': 'PatientGeneralInfoOphthalmology',
                'db_table': 'patient_general_info_ophthalmology',
            },
        ),
        migrations.CreateModel(
            name='PatientGeneralInfoOphthalmologyOcularCompli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.OcularSymptomDt')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ophthalmology.PatientGeneralInfo')),
            ],
            options={
                'verbose_name_plural': 'PatientGeneralInfoOphthalmologyOcularCompli',
                'db_table': 'patient_general_info_ophthalmology_ocular_compli',
            },
        ),
        migrations.CreateModel(
            name='PatientGeneralInfoOphthalmologySystAbnormality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'PatientGeneralInfoOphthalmologySystAbnormality',
                'db_table': 'patient_general_info_ophthalmology_syst_abnormality',
            },
        ),
        migrations.CreateModel(
            name='PatientOtherCommonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_sequencing_1_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('direct_sequencing_2_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('direct_sequencing_3_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('direct_sequencing_4_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('direct_sequencing_5_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('targt_enrichment_ngs_panel_1_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('targt_enrichment_ngs_panel_analysis_1_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('targt_enrichment_ngs_panel_2_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('targt_enrichment_ngs_panel_analysis_2_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('targt_enrichment_ngs_panel_3_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('targt_enrichment_ngs_panel_analysis_3_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('targt_enrichment_ngs_panel_4_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('targt_enrichment_ngs_panel_analysis_4_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('targt_enrichment_ngs_panel_5_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('targt_enrichment_ngs_panel_analysis_5_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('targt_exome_sequencing_1_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('targt_exome_sequencing_analysis_1_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('targt_exome_sequencing_2_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('targt_exome_sequencing_analysis_2_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('exome_sequencing_1_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('exome_sequencing_analysis_1_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('whole_exome_sequencing_1_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('whole_exome_sequencing_analysis_1_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('sequencing_other_collaborators_1_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('sequencing_other_collaborators_analysis_1_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('sequencing_other_collaborators_2_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('sequencing_other_collaborators_analysis_2_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('beadarray_platform_1_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('beadarray_platform_analysis_1_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('other_sequencing_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('mitochondria_ngs_whole_gene_sequence_1_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('mitochondria_ngs_whole_gene_sequence_analysis_1_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('targt_mitochondrial_sequence_2_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('targt_mitochondrial_sequence_analysis_2_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('targt_mitochondrial_hot_spot_panel_sequence_3_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('targt_mitochondrial_hot_spot_panel_sequence_analysis_3_comments', models.CharField(blank=True, max_length=45, null=True)),
                ('other_analysis_comments', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'PatientOtherCommonInfo',
                'db_table': 'patient_other_common_info',
            },
        ),
        migrations.CreateModel(
            name='PatientOtherMultiVisitImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('field_direction', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ophthalmology.PatientGeneralInfo')),
            ],
            options={
                'verbose_name_plural': 'PatientOtherMultiVisitImages',
                'db_table': 'patient_other_multi_visit_images',
            },
        ),
        migrations.CreateModel(
            name='PatientOtherUncommonInfoOphthalmology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_corneal_surgery_perf_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.AgeForSurgeryDt')),
                ('age_corneal_surgery_perf_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.AgeForSurgeryDt')),
                ('age_glaucoma_surgery_perf_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.AgeForSurgeryDt')),
                ('age_glaucoma_surgery_perf_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.AgeForSurgeryDt')),
                ('age_ocul_medi_internal_perf_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.AgeForSurgeryDt')),
                ('age_ocul_medi_internal_perf_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.AgeForSurgeryDt')),
                ('age_ocul_medi_topical_perf_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.AgeForSurgeryDt')),
                ('age_ocul_medi_topical_perf_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.AgeForSurgeryDt')),
                ('age_ocul_surgeries_lasers_perf_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.AgeForSurgeryDt')),
                ('age_ocul_surgeries_lasers_perf_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.AgeForSurgeryDt')),
                ('age_opht_medi_subtenon_subconj_injec_perf_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.AgeForSurgeryDt')),
                ('age_opht_medi_subtenon_subconj_injec_perf_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.AgeForSurgeryDt')),
                ('age_vitreoretina_surgery_perf_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.AgeForSurgeryDt')),
                ('age_vitreoretina_surgery_perf_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.AgeForSurgeryDt')),
                ('no_corneal_surgery_perf_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.NumberOfSurgeryDt')),
                ('no_corneal_surgery_perf_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.NumberOfSurgeryDt')),
                ('no_glaucomal_surgery_perf_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.NumberOfSurgeryDt')),
                ('no_glaucomal_surgery_perf_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.NumberOfSurgeryDt')),
                ('no_ocul_medi_internal_perf_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.NumberOfSurgeryDt')),
                ('no_ocul_medi_internal_perf_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.NumberOfSurgeryDt')),
                ('no_ocul_medi_topical_perf_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.NumberOfSurgeryDt')),
                ('no_ocul_medi_topical_perf_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.NumberOfSurgeryDt')),
                ('no_ofocul_surgeries_lasers_perf_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.NumberOfSurgeryDt')),
                ('no_ofocul_surgeries_lasers_perf_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.NumberOfSurgeryDt')),
                ('no_opht_medi_subtenon_subconj_injec_perf_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.NumberOfSurgeryDt')),
                ('no_opht_medi_subtenon_subconj_injec_perf_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.NumberOfSurgeryDt')),
                ('no_vitreoretinal_surgery_perf_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.NumberOfSurgeryDt')),
                ('no_vitreoretinal_surgery_perf_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.NumberOfSurgeryDt')),
                ('ocul_medi_internal_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.OcularMedicationInternalDt')),
                ('ocul_medi_internal_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.OcularMedicationInternalDt')),
                ('ocul_medi_topical_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.OcularMedicationTopicalDt')),
                ('ocul_medi_topical_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.OcularMedicationTopicalDt')),
                ('ocul_surgeries_cornea_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.OcularSurgeriesCorneaDt')),
                ('ocul_surgeries_cornea_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.OcularSurgeriesCorneaDt')),
                ('ocul_surgeries_glaucoma_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.OcularSurgeriesGlaucomaDt')),
                ('ocul_surgeries_glaucoma_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.OcularSurgeriesGlaucomaDt')),
                ('ocul_surgeries_lasers_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.OcularSurgeriesLasersDt')),
                ('ocul_surgeries_lasers_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.OcularSurgeriesLasersDt')),
                ('ocul_surgeries_retina_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.OcularSurgeriesRetinaDt')),
                ('ocul_surgeries_retina_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.OcularSurgeriesRetinaDt')),
                ('opht_medi_subtenon_subconj_injec_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.OphthalmicMedicationSubtenonOrSubconjunctivalInjectionDt')),
                ('opht_medi_subtenon_subconj_injec_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.OphthalmicMedicationSubtenonOrSubconjunctivalInjectionDt')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ophthalmology.PatientGeneralInfo')),
            ],
            options={
                'verbose_name_plural': 'PatientOtherUncommonInfoOphthalmology',
                'db_table': 'patient_other_uncommon_info_ophthalmology',
            },
        ),
        migrations.CreateModel(
            name='PresentUnpresentDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'PresentUnpresentDt',
                'db_table': 'present_unpresent_dt',
            },
        ),
        migrations.CreateModel(
            name='ProgressionDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'ProgressionDt',
                'db_table': 'progression_dt',
            },
        ),
        migrations.CreateModel(
            name='RefractiveErrorSphericalEquivalentClassificationDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'RefractiveErrorSphericalEquivalentClassificationDt',
                'db_table': 'refractive_error_spherical_equivalent_classification_dt',
            },
        ),
        migrations.CreateModel(
            name='RefractiveErrorSphericalEquivalentDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'RefractiveErrorSphericalEquivalentDt',
                'db_table': 'refractive_error_spherical_equivalent_dt',
            },
        ),
        migrations.CreateModel(
            name='RelationshipToProbandDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'RelationshipToProbandDt',
                'db_table': 'relationship_to_proband_dt',
            },
        ),
        migrations.CreateModel(
            name='SequencingDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'SequencingDt',
                'db_table': 'sequencing_dt',
            },
        ),
        migrations.CreateModel(
            name='SequencingStatusDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'SequencingStatusDt',
                'db_table': 'sequencing_status_dt',
            },
        ),
        migrations.CreateModel(
            name='SexDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'SexDt',
                'db_table': 'sex_dt',
            },
        ),
        migrations.CreateModel(
            name='StaticPerimetryMeanSensitivityClassificationDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'StaticPerimetryMeanSensitivityClassificationDt',
                'db_table': 'static_perimetry_mean_sensitivity_classification_dt',
            },
        ),
        migrations.CreateModel(
            name='StaticPerimetryMeanSensitivityDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'StaticPerimetryMeanSensitivityDt',
                'db_table': 'static_perimetry_mean_sensitivity_dt',
            },
        ),
        migrations.CreateModel(
            name='SubDiseaseDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ophthalmology.DiseaseDt')),
            ],
            options={
                'verbose_name_plural': 'SubDiseaseDt',
                'db_table': 'sub_disease_dt',
            },
        ),
        migrations.CreateModel(
            name='SyndromicDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'SyndromicDt',
                'db_table': 'syndromic_dt',
            },
        ),
        migrations.CreateModel(
            name='SystemicAbnormalityDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'SystemicAbnormalityDt',
                'db_table': 'systemic_abnormality_dt',
            },
        ),
        migrations.CreateModel(
            name='TypicalDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'TypicalDt',
                'db_table': 'typical_dt',
            },
        ),
        migrations.CreateModel(
            name='VisualAcuityClassificationDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'VisualAcuityClassificationDt',
                'db_table': 'visual_acuity_classification_dt',
            },
        ),
        migrations.CreateModel(
            name='VisualAcuityDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'VisualAcuityDt',
                'db_table': 'visual_acuity_dt',
            },
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='beadarray_platform_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='beadarray_platform_analysis_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='direct_sequencing_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='direct_sequencing_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='direct_sequencing_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='direct_sequencing_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='direct_sequencing_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='exome_sequencing_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='exome_sequencing_analysis_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='mitochondria_ngs_whole_gene_sequence_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='mitochondria_ngs_whole_gene_sequence_analysis_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='other_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='other_sequencing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ophthalmology.PatientGeneralInfo'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='sequencing_other_collaborators_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='sequencing_other_collaborators_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='sequencing_other_collaborators_analysis_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='sequencing_other_collaborators_analysis_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_analysis_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_analysis_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_analysis_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_analysis_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_analysis_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_exome_sequencing_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_exome_sequencing_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_exome_sequencing_analysis_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_exome_sequencing_analysis_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_mitochondrial_hot_spot_panel_sequence_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_mitochondrial_hot_spot_panel_sequence_analysis_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_mitochondrial_sequence_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_mitochondrial_sequence_analysis_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='whole_exome_sequencing_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='whole_exome_sequencing_analysis_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingStatusDt'),
        ),
        migrations.AddField(
            model_name='patientgeneralinfoophthalmologysystabnormality',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.SystemicAbnormalityDt'),
        ),
        migrations.AddField(
            model_name='patientgeneralinfoophthalmologysystabnormality',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ophthalmology.PatientGeneralInfo'),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='progression',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophthalmology.ProgressionDt'),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='relationship_to_proband',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophthalmology.RelationshipToProbandDt'),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='sequencing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophthalmology.SequencingDt'),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophthalmology.SexDt'),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='syndromic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophthalmology.SyndromicDt'),
        ),
        migrations.AddField(
            model_name='patientcausativegeneinfo',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ophthalmology.PatientGeneralInfo'),
        ),
        migrations.AddField(
            model_name='patientcandidategenemutationinfo',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ophthalmology.PatientGeneralInfo'),
        ),
    ]
