# Generated by Django 2.1.4 on 2018-12-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0002_auto_20181218_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientgeneralinfoophthalmologyocularcompli',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfoophthalmologyocularcompli',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfoophthalmologysystabnormality',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfoophthalmologysystabnormality',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
