# Generated by Django 2.1.4 on 2018-12-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0003_auto_20181218_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientgeneralinfofamily',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
