# Generated by Django 2.1.4 on 2018-12-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0004_auto_20181218_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientgeneralinfoophthalmologyocularcompli',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='patientgeneralinfoophthalmologysystabnormality',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
