# Generated by Django 2.1.4 on 2018-12-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0006_auto_20181218_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientgeneralinfo',
            name='registration_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
