# Generated by Django 2.1.4 on 2018-12-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0007_auto_20181218_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientgeneralinfo',
            name='birth_year_month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
