# Generated by Django 2.1.4 on 2018-12-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0009_auto_20181219_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientgeneralinfoophthalmology',
            name='age_at_onset_of_ocul_symp_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfoophthalmology',
            name='age_at_the_init_diag_clas_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfoophthalmology',
            name='age_at_the_init_diag_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfoophthalmology',
            name='age_catrct_surgery_perf_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfoophthalmology',
            name='age_catrct_surgery_perf_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfoophthalmology',
            name='no_catrct_surgery_perf_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfoophthalmology',
            name='no_catrct_surgery_perf_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfoophthalmology',
            name='ocul_surgeries_catrct_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfoophthalmology',
            name='ocul_surgeries_catrct_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfoophthalmology',
            name='onset_of_diease_clas_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
