# Generated by Django 2.1.4 on 2019-01-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0018_institutedt_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdiseasedt',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
