# Generated by Django 2.1.3 on 2019-01-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0020_adminsubdiseasedt_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientgeneralinfo',
            name='registration',
        ),
        migrations.AddField(
            model_name='patientcausativegeneinfo',
            name='caus_cand_gene_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientcausativegeneinfo',
            name='caus_cand_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientcausativegeneinfo',
            name='chromosome_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientcausativegeneinfo',
            name='exon_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientcausativegeneinfo',
            name='type_old_new_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
