# Generated by Django 2.1.3 on 2019-01-31 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0023_auto_20190131_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasecauscandgenedt',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophthalmology.AdminDiseaseDt'),
        ),
    ]
