# Generated by Django 2.1.4 on 2018-12-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='registration_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
