# Generated by Django 2.1.4 on 2018-12-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0005_auto_20181218_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientgeneralinfo',
            name='is_draft',
            field=models.BooleanField(default=0),
        ),
    ]
