# Generated by Django 2.1.4 on 2018-12-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0008_auto_20181219_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='beadarray_platform_1_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='beadarray_platform_analysis_1_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='direct_sequencing_1_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='direct_sequencing_2_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='direct_sequencing_3_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='direct_sequencing_4_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='direct_sequencing_5_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='exome_sequencing_1_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='exome_sequencing_analysis_1_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='mitochondria_ngs_whole_gene_sequence_1_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='mitochondria_ngs_whole_gene_sequence_analysis_1_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='other_analysis_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='other_sequencing_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='sequencing_other_collaborators_1_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='sequencing_other_collaborators_2_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='sequencing_other_collaborators_analysis_1_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='sequencing_other_collaborators_analysis_2_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_1_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_2_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_3_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_4_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_5_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_analysis_1_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_analysis_2_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_analysis_3_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_analysis_4_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_enrichment_ngs_panel_analysis_5_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_exome_sequencing_1_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_exome_sequencing_2_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_exome_sequencing_analysis_1_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_exome_sequencing_analysis_2_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_mitochondrial_hot_spot_panel_sequence_3_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_mitochondrial_hot_spot_panel_sequence_analysis_3_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_mitochondrial_sequence_2_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='targt_mitochondrial_sequence_analysis_2_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='whole_exome_sequencing_1_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientothercommoninfo',
            name='whole_exome_sequencing_analysis_1_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
