# Generated by Django 2.1.4 on 2018-12-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0010_auto_20181220_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='age_corneal_surgery_perf_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='age_corneal_surgery_perf_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='age_glaucoma_surgery_perf_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='age_glaucoma_surgery_perf_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='age_ocul_medi_internal_perf_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='age_ocul_medi_internal_perf_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='age_ocul_medi_topical_perf_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='age_ocul_medi_topical_perf_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='age_ocul_surgeries_lasers_perf_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='age_ocul_surgeries_lasers_perf_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='age_opht_medi_subtenon_subconj_injec_perf_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='age_opht_medi_subtenon_subconj_injec_perf_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='age_vitreoretina_surgery_perf_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='age_vitreoretina_surgery_perf_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='no_corneal_surgery_perf_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='no_corneal_surgery_perf_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='no_glaucomal_surgery_perf_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='no_glaucomal_surgery_perf_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='no_ocul_medi_internal_perf_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='no_ocul_medi_internal_perf_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='no_ocul_medi_topical_perf_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='no_ocul_medi_topical_perf_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='no_ofocul_surgeries_lasers_perf_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='no_ofocul_surgeries_lasers_perf_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='no_opht_medi_subtenon_subconj_injec_perf_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='no_opht_medi_subtenon_subconj_injec_perf_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='no_vitreoretinal_surgery_perf_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='no_vitreoretinal_surgery_perf_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='ocul_medi_internal_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='ocul_medi_internal_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='ocul_medi_topical_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='ocul_medi_topical_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='ocul_surgeries_cornea_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='ocul_surgeries_cornea_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='ocul_surgeries_glaucoma_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='ocul_surgeries_glaucoma_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='ocul_surgeries_lasers_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='ocul_surgeries_lasers_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='ocul_surgeries_retina_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='ocul_surgeries_retina_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='opht_medi_subtenon_subconj_injec_left_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientotheruncommoninfoophthalmology',
            name='opht_medi_subtenon_subconj_injec_right_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
