# Generated by Django 2.1.4 on 2018-12-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0011_auto_20181220_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='affected_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='analysis_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='bilateral_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='consanguineous_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='country_of_origine_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='disease_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='dna_extraction_process_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='ethnic_of_father_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='ethnic_of_mother_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='ethnicity_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='family_history_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='flactuation_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='gene_type_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='inheritance_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='inheritance_type_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='mutation_type_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='number_of_affected_members_in_the_same_pedigree_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='ocular_symptom_1_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='ocular_symptom_2_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='ocular_symptom_3_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='origin_of_father_in_japan_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='origin_of_mother_in_japan_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='origin_prefecture_in_japan_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='original_country_of_father_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='original_country_of_mother_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='progression_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='relationship_to_proband_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='sequencing_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='sex_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgeneralinfo',
            name='syndromic_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
