# Generated by Django 2.1.4 on 2018-12-20 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0012_auto_20181220_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausCandDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'CausCandDt',
                'db_table': 'caus_cand_dt',
            },
        ),
        migrations.CreateModel(
            name='TypeOldNewDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'TypeOldNewDt',
                'db_table': 'type_old_new_dt',
            },
        ),
        migrations.RenameField(
            model_name='patientcausativegeneinfo',
            old_name='caus_gene',
            new_name='caus_cand_gene',
        ),
        migrations.RenameField(
            model_name='patientcausativegeneinfo',
            old_name='caus_mutation_nucleotide_change_amino_acid_change',
            new_name='caus_cand_mutation_nucleotide_amino_acid',
        ),
        migrations.AddField(
            model_name='patientcausativegeneinfo',
            name='caus_cand_mutation_nucleotide_amino_acid_comment',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='patientcausativegeneinfo',
            name='chromosome_comment',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='patientcausativegeneinfo',
            name='exon_comment',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='patientcausativegeneinfoethnicity',
            name='freq_ethnicity_other',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='patientcausativegeneinfoethnicity',
            name='freq_ethnicity_per',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='patientcausativegeneinfolocalpopulation',
            name='freq_ethnicity_other',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='patientcausativegeneinfolocalpopulation',
            name='freq_ethnicity_per',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='patientcausativegeneinfo',
            name='type_old_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.TypeOldNewDt'),
        ),
        migrations.AddField(
            model_name='patientcausativegeneinfo',
            name='caus_cand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ophthalmology.CausCandDt'),
        ),
    ]
