# Generated by Django 2.1.4 on 2019-01-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0017_auto_20190107_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutedt',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
