# Generated by Django 2.1.3 on 2019-01-29 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0021_auto_20190124_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsubdiseasedt',
            name='color',
        ),
        migrations.RemoveField(
            model_name='institutedt',
            name='color',
        ),
        migrations.RemoveField(
            model_name='subdiseasedt',
            name='color',
        ),
    ]
